### ISSUE TITLE
Compile from source on Opensuse Tumbleweed Issues

### ISSUE THREAD

**Issue by krionical** [MFernstrom/rTest#2]
Hey, I got this program from your linux build, but before I noticed that I tried to build it from source.

If I fpc main.pas I get 

Fatal: Can't find unit Forms used by main.

If I lazbuild  ./rTest.lpr I get

(1002) Target OS: Darwin for x86_64
(3104) Compiling fcllaz.pas
Fatal: (10022) Can't find unit system used by fcllaz
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Error: (lazarus) Compile package FCL 1.0.1: stopped with exit code 1
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "Exit code 1"
Error: (lazbuild) Project dependencies of /home/shadowmoses/.local/share/Trash/files/rTest.2/source/rTest.lpi

My guess is that somehow, somewhere the build has its heart set on Darwin which is not what this machine runs and so it is looking for something it isn't going to find by default on OpenSuse. 

Of course, I am not extremely well-versed in Pascal and its intricacies, so I might be missing something obvious.

**Comment by MFernstrom** [comment]
The Lazarus project has three build modes. You need to switch build mode to Linux.

Easiest is to use Lazarus and open the project, switch to Linux, and then Build it.

**Comment by krionical** [comment]
Thanks for getting back to me so quickly. For anyone else who comes across this the process is to open rtest.lpr in lazarus, and then  click the gear icon: https://wiki.freepascal.org/IDE_Window:_Compiler_Options#Selecting_the_active_build_mode

Once you do that you can select which build is which. I had a feeling I was missing something simple, but a quick check online indicates many people miss the build mode switcher.
